language: node_js
node_js: ["6"]

install:
  - yarn install

script:
  - yarn lint
  - yarn build
  - yarn test:build
  - DEBUG=true yarn test:coverage

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc

deploy:
  - provider: script
    script: npm run release
    on:
      tags: true
